### ISSUE TITLE
Issue with numpy 1.10

### ISSUE THREAD

**Issue by carreremax** [rougier/dana#8]
Hello,
When upgrading numpy to numpy 1.10 (1.10.0.dev0+4027d16), my neuron model (previously working) encounters the following error :
 C = DenseConnection( la_activities_plus('U'),   cell_on('input_la'),       np.ones((la_size,cell_on_number)) )
  File "/usr/local/lib/python2.7/dist-packages/dana-0.5.1-py2.7.egg/dana/dense_connection.py", line 51, in **init**
    self.setup_weights(weights)
  File "/usr/local/lib/python2.7/dist-packages/dana-0.5.1-py2.7.egg/dana/dense_connection.py", line 80, in setup_weights
    K = convolution_matrix(self.source, self.target, weights, self._toric)
  File "/usr/local/lib/python2.7/dist-packages/dana-0.5.1-py2.7.egg/dana/functions.py", line 331, in convolution_matrix
    indices[0] += np.atleast_2d((np.array(src.shape)//2 - np.array(kernel.shape)//2)).T
TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
This may be caused by the fact that implicit casts are stricter in numpy 1.10 than in previous versions.

**Comment by rougier** [comment]
Can you try to add `.T.astype(np.float64)` instead of `.T` to check if this fix the problem ?

**Comment by carreremax** [comment]
The problem arises when the constructor from dana.ones is used with a float, and the resulting matrix is used in a DenseConnection. Np.ones() is fine.
'''
import dana as dana
import numpy as np

Z=dana.ones(1.0)
K=np.arange(1.0)
C = dana.DenseConnection( Z, Z,K)
'''
